name: esptouch
description: Demonstrates how to use the esptouch plugin.
publish_to: 'none'
version: 0.1.5

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.3
  mqtt_client: ^9.3.1
  network_info_plus: ^1.0.1
  provider: ^5.0.0
  location_permissions: ^3.0.0
  dotted_border: ^2.0.0
  intl: ^0.17.0
dev_dependencies:
  flutter_test:
    sdk: flutter

  esptouch_flutter:
    path: ../

flutter:
  uses-material-design: true
  fonts:
     - family: CustomIcons
       fonts:
         - asset: fonts/CustomIcons.ttf
